host:
  ip:
    rabbitmq: 127.0.0.1
    redis: 127.0.0.1
    nacos: 127.0.0.1
    mysql: 127.0.0.1
spring:
  jackson:
    default-property-inclusion: non_null
  #服务名称
  application:
    name: nacos-provider1
  #nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: ${host.ip.nacos}:8848
  #数据库连接池
  datasource:
    druid:
      username: root
      password: 1234
      url: jdbc:mysql://${host.ip.mysql}:3306/myshop?useSSL=false&useUnicode=true&characterEncoding=utf-8
      initial-size: 10
      max-active: 50
      validation-query: select 1
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
  #redis配置
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    cluster:
      nodes: ${host.ip.redis}:6379
      max-redirects: 3
#    sentinel:
#      master: mymaster
#      nodes: ${host.ip.redis}:26379, ${host.ip.redis}:26380, ${host.ip.redis}:26381
        #MQ配置
  #MQ
  rabbitmq:
    addresses: ${host.ip.rabbitmq}:5672
    connection-timeout: 15000
    password: guest
    username: guest
    publisher-confirms: true
    virtual-host: /
    ##以下两个配置一组
    publisher-returns: true
    template:
      mandatory: true
    #消费者配置
    listener:
      order:
        exchange:
          durable: true
          ignoreDeclarationExceptions: true
          name: exchange-2
          type: topic
        key: springboot.*
        queue:
          durable: true
          name: queue-2
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
server:
  port: 28081

#端点检查
management:
  endpoints:
    web:
      exposure:
        include: "*"

##mybatis配置
mybatis:
  type-aliases-package: com.zlm.hello.spring.cloud.alibaba.nacos.provider.model
  mapper-locations: classpath:mapper/*Mapper*.xml
  configuration:
    cache-enabled: true
logging:
  level:
   com.zlm.hello.spring.cloud.alibaba.nacos.provider.dao : debug

kaptcha:
  #是否有边框，默认为yes，可选yes、no
  border: "yes"
  #边框颜色
  border.color: 105,179,90
  textproducer:
    font:
      #验证码字体颜色
      color: blue
      #文本字符大小
      size: 30
      #文本字体样式
      names: 宋体,楷体,微软雅黑
    char:
      #验证码文本字符长度
      length: 4
  image:
    #图片宽度
    width: 120
    #图片高度
    height: 40
  #session:
    #存储session key
    #key: code
async:
  core_pool_size: 3
  max_pool_size: 5
  queue_capacity: 50
  keep_alive_seconds: 60
  await_termination_seconds: 60