spring:
  #服务名称
  application:
    name: nacos-consumer
  #nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #sentinel监控台配置
    sentinel:
      transport:
        #向监控台暴露的端口
        port: 8719
        #监控台ip
        dashboard: localhost:38080

server:
  port: 29091


#端点检查
management:
  endpoints:
    web:
      exposure:
        include: "*"

